# .streamlit/secrets.toml

[connections.snowflake]
account = "NISUUVN.KW17594"
user = "VIJI"
password = "blueBerry@071983"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
